name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: pytest # Replace this with your test command or script
    - name: Add EC2 instance to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "18.218.13.168 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICJVMq9yKl2O9R3vdCAVEFGO2JjH9LHDK3Cu1gv9fSu9" >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy to AWS EC2
      if: github.ref == 'refs/heads/main' # Only deploy if on the main branch
      env:
        ENVIRONMENT: production
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem ec2-user@$HOST "mkdir -p /home/ec2-user/ai-assistant"
        scp -i private_key.pem -r * ec2-user@$HOST:/home/ec2-user/ai-assistant
        ssh -i private_key.pem ec2-user@$HOST 'bash -s' < deploy.sh

